### ISSUE TITLE
On Install: (node:13734) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by DamageIncorporated** [Klizzy/MMM-Vrr#29]
I don't know if this is a serious issue, but I saw it during installation of  the module and to be safe, I post it anyway:

The following message appears multiple (10+) times in the terminal while running `npm install`:

`(node:13734) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
`
after that, the install seems to finish okay. 

Now I'll try to configure it in my new MM² smart display and see if it works ;-)

**Comment by DamageIncorporated** [comment]
When I try to start  the Magic mirror with this plugin activated, I get the following Error message in terminal:

`[14206:113/14243.54730:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: Datei oder Verzeichnis nicht gefunden(2)`

I hope this helps and it's not me who makes a stupid beginner's error here, but AFAIR I did follow the MM-documentation and this readme carefully.

deactivating the plugin in config.js for now, but ready to help debugging when instructed ;-)

**Comment by morzan1001** [comment]
Hey, I had the same problem. It's a bit silly that with pm2 you only ever see the last 15 lines in the log. I looked at the entire log and found the following error:

```
[2024-12-10 20:26:00.418] [ERROR] (node:1949) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- /home/morzan1001/MagicMirror/modules/MMM-Vrr/node_helper.js
- /home/morzan1001/MagicMirror/js/app.js
- /home/morzan1001/MagicMirror/js/electron.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:121498)
    at Module._resolveFilename (/home/morzan1001/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/morzan1001/MagicMirror/modules/MMM-Vrr/node_helper.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at loadModule (/home/morzan1001/MagicMirror/js/app.js:200:19)
(Use `electron --trace-warnings ...` to show where the warning was created)
[2024-12-10 20:26:00.419] [ERROR] (node:1949) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

I took a closer look and the only problem is that the [request](https://www.npmjs.com/package/request) library is not installed. So I made an `npm install request` in the MagicMirror directory and immediately everything works again :+1:
